#!/bin/bash
export FOLDER=/../../home/ec2-user/new-kitty-items

# if folder exists, delete folder
if [ -d $FOLDER ]
then 
    sudo rm -rf $FOLDER
fi

# create new folder
mkdir -p $FOLDER
cd $FOLDER

# install node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
nvm install --lts

# install flow cli
sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
