#!/bin/bash
export FOLDER=/../../home/ec2-user/new-kitty-items
if [ -d $FOLDER ]
then 
    sudo rm -rf $FOLDER
fi

mkdir -p $FOLDER
cd $FOLDER

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

nvm install --lts