#!/bin/bash
# service httpd start
echo "This is the start"
pwd
cd home/ec2-user/new-kitty-items
pwd

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

~/.nvm/versions/node/v16.16.0/bin/npm install
~/.nvm/versions/node/v16.16.0/bin/npm run dev:testnet
