#!/bin/bash
# service httpd start
export FOLDER=/../../home/ec2-user/new-kitty-items
cd $FOLDER

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# Some linux distributions install nodejs not as "node" executable but as "nodejs".
# In this case you have to manually link to "node" as many packages are programmed after the "node" binary. 
# Something similar also occurs with "python2" not linked to "python".
# In this case you can do an easy symlink. For linux distributions which install package binaries to /usr/bin you can do: 
ln -s /usr/bin/nodejs /usr/bin/node

npm install
npm run dev:testnet

