#!/bin/bash
# isExistApp = `pgrep httpd`
# if [[ -n  $isExistApp ]]; then
#     service httpd stop        
# fi
# export FOLDER=/../../home/ec2-user/new-kitty-items
# cd $FOLDER
# /usr/local/bin/npx pm2 delete all